# Generated by Django 2.2.13 on 2021-04-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obestetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obdate', models.DateField(blank=True, null=True, verbose_name='Follow Up Date:')),
                ('gyn', models.BooleanField(default=False, verbose_name='Gyn:')),
                ('g', models.IntegerField(blank=True, default=0, null=True, verbose_name='G:')),
                ('p', models.IntegerField(blank=True, default=0, null=True, verbose_name='P:')),
                ('a', models.IntegerField(blank=True, default=0, null=True, verbose_name='A:')),
                ('nvd', models.BooleanField(default=False, verbose_name='NVD:')),
                ('cs', models.BooleanField(default=False, verbose_name='CS:')),
                ('ld', models.CharField(blank=True, max_length=150, null=True, verbose_name='LD:')),
                ('lc', models.CharField(blank=True, max_length=150, null=True, verbose_name='LC:')),
                ('hist', models.TextField(blank=True, max_length=250, null=True, verbose_name='History of previous obestetric complication(if any):')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients', verbose_name='Patient Name:')),
            ],
        ),
        migrations.CreateModel(
            name='SurHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Surgical History:')),
                ('obestetric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Menstrual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmp', models.DateField(blank=True, null=True, verbose_name='LMP:')),
                ('edd', models.DateField(blank=True, null=True, verbose_name='EDD:')),
                ('ga', models.CharField(blank=True, max_length=50, null=True, verbose_name='G.A:')),
                ('remain', models.CharField(blank=True, max_length=50, null=True, verbose_name='Remaining Weeks:')),
                ('obestetric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Medical History:')),
                ('obestetric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='GynHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Gynecological History:')),
                ('obestetric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='DrugHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Drug History:')),
                ('obestetric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
    ]
