# Generated by Django 2.2.13 on 2021-02-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0003_auto_20210221_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obestetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyn', models.BooleanField(default=False)),
                ('g', models.IntegerField(blank=True, default=0, null=True)),
                ('p', models.IntegerField(blank=True, default=0, null=True)),
                ('a', models.IntegerField(blank=True, default=0, null=True)),
                ('nvd', models.BooleanField(default=False)),
                ('cs', models.BooleanField(default=False)),
                ('ld', models.CharField(blank=True, max_length=150, null=True)),
                ('lc', models.CharField(blank=True, max_length=150, null=True)),
                ('hist', models.CharField(blank=True, max_length=250, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='SurHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('obestetric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='Menstrual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmp', models.DateField(blank=True, null=True)),
                ('edd', models.DateField(blank=True, null=True)),
                ('ga', models.IntegerField(blank=True, default=0, null=True)),
                ('remain', models.IntegerField(blank=True, default=0, null=True)),
                ('obestetric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('obestetric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='GynHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('obestetric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
        migrations.CreateModel(
            name='DrugHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('obestetric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
    ]
