# Generated by Django 2.2.13 on 2021-03-01 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drughistory',
            name='name',
            field=models.CharField(blank=True, help_text='Drug History', max_length=150, null=True, verbose_name='Drug History'),
        ),
        migrations.AlterField(
            model_name='drughistory',
            name='obestetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric'),
        ),
        migrations.AlterField(
            model_name='drughistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients'),
        ),
        migrations.AlterField(
            model_name='gynhistory',
            name='name',
            field=models.CharField(blank=True, help_text='Gyn History', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='gynhistory',
            name='obestetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric'),
        ),
        migrations.AlterField(
            model_name='gynhistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients'),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='obestetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric'),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients'),
        ),
        migrations.AlterField(
            model_name='menstrual',
            name='obestetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric'),
        ),
        migrations.AlterField(
            model_name='menstrual',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients'),
        ),
        migrations.AlterField(
            model_name='obestetric',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patientdata.Patients'),
        ),
        migrations.AlterField(
            model_name='surhistory',
            name='obestetric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gyno.Obestetric'),
        ),
        migrations.AlterField(
            model_name='surhistory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients'),
        ),
    ]
