# Generated by Django 2.2.13 on 2021-03-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyno', '0002_auto_20210301_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drughistory',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Drug History'),
        ),
        migrations.AlterField(
            model_name='gynhistory',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Gynecological History'),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Medical History'),
        ),
        migrations.AlterField(
            model_name='obestetric',
            name='gyn',
            field=models.BooleanField(default=False, verbose_name='Gyna'),
        ),
        migrations.AlterField(
            model_name='obestetric',
            name='hist',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='History of previous obestetric complication(if any)'),
        ),
        migrations.AlterField(
            model_name='obestetric',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients', verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='surhistory',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Surgical History'),
        ),
    ]
