# Generated by Django 2.2.13 on 2021-02-18 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('age', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('phone', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(blank=True, max_length=150, null=True)),
                ('cardid', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
