# Generated by Django 2.2.13 on 2021-04-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
