# Generated by Django 2.2.13 on 2021-02-21 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 2, 21), null=True),
        ),
    ]
