# Generated by Django 2.2.13 on 2021-04-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0006_auto_20210405_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='barimg',
            field=models.ImageField(blank=True, null=True, upload_to='patients'),
        ),
    ]
