# Generated by Django 2.2.13 on 2021-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0007_auto_20210407_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
