# Generated by Django 2.2.13 on 2021-04-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0008_auto_20210411_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='barurl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
