# Generated by Django 2.2.13 on 2021-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdata', '0009_auto_20210411_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
