# Generated by Django 2.2.13 on 2021-04-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labvisit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='labs'),
        ),
    ]
