# Generated by Django 2.2.13 on 2021-02-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0002_auto_20210221_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Add Drug Here Please ....', max_length=100, null=True)),
                ('plan', models.CharField(blank=True, max_length=150, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
    ]
