# Generated by Django 2.2.13 on 2021-02-21 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0002_auto_20210221_1423'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('complain', models.TextField(blank=True, null=True)),
                ('sign', models.TextField(blank=True, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=150, null=True)),
                ('intervention', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.Visits')),
            ],
        ),
    ]
