# Generated by Django 2.2.13 on 2021-02-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookdate', models.DateField()),
                ('starttime', models.CharField(blank=True, max_length=20, null=True)),
                ('endtime', models.CharField(blank=True, max_length=20, null=True)),
                ('booknum', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
    ]
