# Generated by Django 2.2.13 on 2021-02-18 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasthist', models.CharField(blank=True, max_length=150, null=True)),
                ('histdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('remarknote', models.CharField(blank=True, max_length=1000, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
            ],
        ),
    ]
