# Generated by Django 2.2.13 on 2021-02-18 19:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientdata', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('temprature', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('height', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3)),
                ('cholestrol', models.CharField(blank=True, max_length=150, null=True)),
                ('pulse', models.CharField(blank=True, max_length=150, null=True)),
                ('bloodpr', models.CharField(blank=True, max_length=150, null=True)),
                ('bsl', models.CharField(blank=True, max_length=150, null=True)),
                ('hb', models.CharField(blank=True, max_length=150, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patientdata.Patients')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visits.Visits')),
            ],
        ),
    ]
